### ISSUE TITLE
Got this error on the chess AI. No idea how to fix it. Please help!

### ISSUE THREAD

**Issue by Tiger-Tom** [Dirk94/ChessAI#2]
Traceback (most recent call last):
  File "E:\###I\main.py", line 39, in <module>
    move = get_valid_user_move(board)
  File "E:\###\main.py", line 22, in get_valid_user_move
    possible_moves = board.get_possible_moves(pieces.Piece.WHITE)
  File "E:\###\board.py", line 61, in get_possible_moves
    moves = moves + piece.get_possible_moves(self)
  File "E:\###\pieces.py", line 83, in get_possible_moves
    return self.get_possible_horizontal_moves(board)
  File "E:\###I\pieces.py", line 41, in get_possible_horizontal_moves
    for i in range(1, board.Board.WIDTH - self.x):
AttributeError: 'Board' object has no attribute 'Board'

**Comment by ankith26** [comment]
Even i get similar errors. Maybe the code is designed for some older version of python. Which version do you use

**Comment by Tiger-Tom** [comment]
Python 3.7

**Comment by Tiger-Tom** [comment]
README.md said that this code was written for Python3, so it should work with 3.7

**Comment by ankith26** [comment]
One solution is replacing all 'board.Board.WIDTH' and 'board.Board.HEIGHT'  variables with the value 8.

I am currently trying that

**Comment by Dirk94** [comment]
The issue has been fixed. It was originally written in Python3, I've updated the source code to Python3 now.
